### ISSUE TITLE
install

### ISSUE THREAD

**Issue by pertuk** [pyner/admin_plus#2]
I'm getting an error while following the readme  
   
>    2. go to "127.0.0.1:8000/<app>/plugin_admin_plus/install"

I install the plugin, start the w2py server. My app is "ipcost", so I pont to 

>   http://127.0.0.1:8000/ipcost/plugin_admin_plus/install

This message error is what I get:

>    invalid controller (plugin_admin_plus/install)

No further action can be taken.
Any clue will be appreciate.
Greets

**Comment by pyner** [comment]
"plugin_admin_plus/install" : this controller executes the function  [create_roles()](https://github.com/pyner/admin_plus/blob/master/models/plugin_admin_plus.py#L114)

**Comment by pyner** [comment]
the problem may be your url configuration, go manually to the plugin interface, try that :

http://localhost:8000/admin/default/plugin/<<APP>>/admin_plus?id=plugins__admin_plus&id2=plugins

where <<APP>> is the name of your application, then go to install link in the controller
